2004GHPTeam8Sogr8/GraceShopper

README.md, norms.txt, tier details.md
---
Hi team! I create a text file with our group norms, and another file called "tier details" that has all the tier descriptions for Grace Shopper!
=> create norms and tier details

.travis.yml, package.json, server/db/models/user.js
---
Hi team! I updated the user model with this morning based on our wire frame. Let's check in with Jen about whether credit card should live on the user model after lunch!
=> update user model

.travis.yml, package.json, server/db/models/orderHistory.js
---
I added an Order model definition based on the original schema we aligned on.  We will still need to consider how we want to generate the orderId. We may want to add a method on the Order model to help with this.
=> created orderHistory model

.travis.yml, package-lock.json, package.json, server/db/models/Inventory.js
=> Inventory model

server/db/models/cart.js
---
Created the Cart model for associating Users and Inventory.
=> created cart model

server/api/index.js, server/api/products.js
---
-Wrote GET routes for single product and all products
-Will likely need to add more routes to this file to handle changes to inventory
=> added GET routes for single product and all products

client/components/OrderConfirmation.js, client/components/checkout.js, client/routes.js
---
Just a little component that shows users their order has been confirmed!
=> create OrderConfirmation component

client/components/cart-item.js, client/components/cart.js, client/store/cart.js, client/store/index.js, server/api/cart.js, server/db/models/product_order.js
---
Cart functionality!
- GET, PUT, DELETE routes written and tested **(note: POST route has not been finalized/tested)**
- Redux reducer for cart added
- React components connected
=> Cart routes

server/api/products.js
=> updated product.js with correct model name

client/components/AllProducts.js, client/components/single-product.js, client/store/cart.js, client/store/index.js, server/api/cart.js
---
So we did a things:
- fixed key error issue on all products component
- did everything that was needed to make add to cart functionality work correctly
=> addToCart from single product view for logged in user working correctly

server/api/users.spec.js, server/db/models/user.spec.js
---
Hello fine Coder,
We simply helped the given test the information they need to pass!
Sincerely,
Katie and Naomi
=> failing tests now pass on localhost

client/components/Checkout.js, client/components/Stripe.js, client/store/cart.js, package-lock.json, package.json, server/api/cart.js
---
Hi team! checkout now has a working data flow, after git pull origin master, restart localhost!!
=> Stripe: checkout

client/components/cart-item.js, client/components/cart.js, client/store/cart.js, server/api/cart.js
=> Cart Routes Refactor

client/components/AllProducts.spec.js, client/store/singleProduct.spec.js, server/api/products.spec.js
[ yes ] added unit tests
---
Made tests for the products slice. All tests are passing. One is pending b/c need to do research on setting up virtual store, etc, and wanted to push the completed tests we have. AllProducts.spec.js is the file that has most of the code that is needed for the test
=> Products tests

client/components/Checkout.js, client/components/OrderConfirmation.js
---
Hi team, updated 3 buttons in the checkout flow! now on the checkout page users. can go back to cart or submit order to get to the confirmation page. Once on the confirmation page they can start a new order.
=> Checkout buttons and confirmation button

client/components/Checkout.js
=> update form input fields

client/components/auth-form.js, client/store/user.js, server/api/cart.spec.js, server/auth/index.js
First pass at adding basic user signup functionality. When user signs up, they are auto logged in and their information is stored in db. 
---
There are plenty of optimizations and validations that can be made, but this should work well enough for now!
=> Signup user

client/components/AllProducts.js, client/components/auth-form.js, client/components/navbar.js, client/components/single-product.js, client/store/user.js, server/api/cart.spec.js, server/auth/index.js
Hello!
Used Semeantic React UI to style all products and single product view. Expect that we might change details here or there, but overall think it looks better.
Cheers,
Kate
---
=> Style products

client/components/Admin.js, client/components/AdminAddProduct.js, client/components/AdminUpdateProduct.js, client/components/AdminUserView.js, client/routes.js
=> Admin dashboard component

client/components/Checkout.js, client/store/cart.js, server/api/cart.js
---
Hi team! Checkout now works backend, frontend, any direction you want it to be!!!
=> Checkout form updates order database

client/components/auth-form.js, client/components/navbar.js, client/store/user.js, server/api/cart.spec.js, server/auth/index.js
Hi!
This branch if merged should correct the data flow problems I created with my earlier code. I also adapted the api/cart route test to allow for the test results to pass. 
Cheers,
Kate
=> New fix login refresh

client/components/single-product.js, script/productSeed.js
npm run seed after you pull!
---
Hi team! The seed files are finalized!
=> update product descript and added dollar sign in single product view

client/components/cart-item.js
Hi!
We have an image now in the cart that represents the items, all other functions still work. Also refactored the ui to have some improvements, but could be improved more.
=> image added to cart and small ui optimizations

client/components/home.js
Did the above to make it prettier.
---
=> finished link to collection and some carosel image links

client/store/user.js, server/auth/index.js
=> sign up is working again

client/components/navbar.js
feat: added Hi name in navbar
lovely little feat that lets user know they are logged and welcomed!
=> name shows up when logged in by logout button

client/components/Admin.js, client/components/Checkout.js, client/components/cart-item.js, client/components/cart.js, client/components/single-product.js, script/makeTotalStr.js
Made a function to help with the trailing zero problem and correct it and have a new function available for any new pages that need it in the future.
=> Fix calculations
